/* ABOUTME: Files embedded into tt7d at build time: the control panel's HTML/CSS/JS and the test pattern.
 * ABOUTME: The table is generated by tt7d/embed.py from tt7d/web/ (see the Makefile); lookup is by exact name. */
#ifndef TT7D_ASSETS_H
#define TT7D_ASSETS_H

#include <stddef.h>

struct asset {
    const char *name; /* a URL path ("/", "/panel.js") or an internal name without a leading '/' */
    const char *content_type;
    const unsigned char *data;
    size_t len;
};

/* The built-in test pattern PNG (tools/make-test-frame.py at build time).
 * No leading '/', so no request path can fetch it as a file. */
#define ASSET_TEST_PATTERN "test-pattern.png"

extern const struct asset assets[];
extern const size_t assets_count;

/* The asset with exactly this name, or NULL. */
const struct asset *asset_find(const char *name);

#endif
