#!/usr/bin/env python3
# ABOUTME: Writes a C file that embeds files into tt7d as a table of struct asset (tt7d/assets.h).
# ABOUTME: Run by the Makefile: embed.py OUT.c NAME=PATH ...; the content type comes from PATH's extension.
"""Usage: tt7d/embed.py OUT.c NAME=PATH [NAME=PATH ...]

NAME is what asset_find() looks up: a URL path such as "/" or "/panel.js",
or an internal name without a leading "/" (never reachable over HTTP).
The output is deterministic, so the same inputs give the same binary.
"""
import os
import sys

TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".png": "image/png",
    ".ttf": "font/ttf",
}


def c_string(s):
    if any(c in s for c in '"\\') or not s.isprintable():
        raise SystemExit(f"embed.py: unsupported character in {s!r}")
    return f'"{s}"'


def main(argv):
    if len(argv) < 3 or any("=" not in a for a in argv[2:]):
        print(__doc__, file=sys.stderr)
        return 2
    out, pairs = argv[1], [a.split("=", 1) for a in argv[2:]]
    lines = ["/* Generated by tt7d/embed.py. Do not edit. */", '#include "assets.h"', ""]
    rows = []
    for i, (name, path) in enumerate(pairs):
        ext = os.path.splitext(path)[1]
        if ext not in TYPES:
            print(f"embed.py: no content type for {path}", file=sys.stderr)
            return 1
        with open(path, "rb") as f:
            data = f.read()
        lines.append(f"/* {name} <- {os.path.basename(path)}, {len(data)} bytes */")
        lines.append(f"static const unsigned char asset_{i}[] = {{")
        for off in range(0, len(data), 16):
            lines.append("    " + ",".join(str(b) for b in data[off:off + 16]) + ",")
        lines.append("};")
        rows.append(f"    {{{c_string(name)}, {c_string(TYPES[ext])}, asset_{i}, sizeof asset_{i}}},")
    lines += ["", "const struct asset assets[] = {", *rows, "};",
              "const size_t assets_count = sizeof assets / sizeof assets[0];", ""]
    tmp = out + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(lines))
    os.replace(tmp, out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
